### ISSUE TITLE
Erros problemáticos de associação pro Streamer

### ISSUE THREAD

**Issue by LeDragoX** [TreinaDev/stream-alpha#115]
Um Streamer, não deveria, mas está podendo cadastrar vídeos sem ter Perfil.
- A associação de Vídeo está ligada ao Streamer, mas se fosse pelo Streamer Profile, ele só poderia criar caso tivesse um perfil completo.
- Necessita trocar a associação de video `belongs_to` de `:streamer` para `:streamer_profile`
- Assim será garantido que haverá o perfil terá as características do dono, e que este estará cadastrado corretamente.

**Comment by OtavioLins** [comment]
Parte 1:
Em vez de trocar a associação, não dá só para fazer um before_action no create do vídeo se checa se o perfil de um streamer está completo?

Parte 2:
Não entendi porque um preço tem que ter muitos vídeos. Todos vídeos avulsos tem o mesmo preço? Se não, isso não faz muito sentido para mim. Do jeito que eu vejo, criaria o preço a partir do vídeo ser avulso e colocaria um valor para ele, independente de algum outro vídeo ter valor igual. Não sei se só não entendi o que você quis dizer, porém.

**Comment by LeDragoX** [comment]
Bom, agora que eu pensei um pouco, não existe problema no preço, e sim no factory bot dele porque é um nested attribute, então era pra isso estar dentro de Video, no factory bot dele, porque se criar um separado, dá muito ruim.
