### ISSUE TITLE
Adicionar GameCategory aos videos

### ISSUE THREAD

**Issue by DaniloJNS** [TreinaDev/stream-alpha#49]
Fazer a associação de GameCategory para Video
Ex: Video `has_many :game_categories`
> Se não for exatamente isso, pode corrigir

_EDIT, categorias de jogo já aparecem na página de um vídeo, através de Jogo_

**Comment by LeDragoX** [comment]
![image](https://user-images.githubusercontent.com/27643047/143506073-0c5204a3-f51a-49c4-ad8d-872a28490909.png)
