### ISSUE TITLE
Cadastro de playlists

### ISSUE THREAD

**Issue by OtavioLins** [TreinaDev/stream-alpha#58]
Cada Playlist deve conter:
- Nome
- Descrição completa
- Streamers que possuem **vídeos (associação)** nessa playlist
- Imagem de capa para divulgação
- etc. ???

As playlists podem ser categorizadas. As categorias podem ter subcategorias.
Uma categoria pode ser desativada temporariamente.
Os vídeos/playlists de uma categoria suspensa não devem ser visualizados na plataforma.

Uma playlist pode estar relacionada a outras playlists e essa informação deve gerar recomendações automáticas para os assinantes.

### Fluxo
Um administrador da plataforma pode cadastrar playlists para serem oferecidas aos assinantes da plataforma.

**Comment by LeDragoX** [comment]
Issue repetido de #20, fechando.
